name: chatt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  quiver: ^3.2.1
  kiwi: ^4.1.0
  json_serializable: ^6.7.0
  json_annotation: ^4.9.0
  intl: ^0.19.0

  bloc: ^8.1.2
  shared_preferences: ^2.2.2
  auto_route: ^7.8.0
  intl_phone_number_input: ^0.7.3+1
  introduction_screen: ^3.1.12
  rflutter_alert: ^2.0.7
  appwrite: ^9.0.0
  otp_text_field: ^1.1.3
  flutter_svg: ^2.0.6
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  js: ^0.6.7
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  salomon_bottom_bar: ^3.3.2
  flutter_hooks: ^0.18.6
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  flutter_pdfview: ^1.3.2
  http: ^0.13.5
  file_picker: ^5.3.1
  path: ^1.7.0
  path_provider: ^2.0.13
  localstorage: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
